import { useEffect, useState } from 'react'
import { getFavorites, getInquiries, getMyListings, loginAccount, registerAccount, replyToInquiry, resetPassword } from '../api.js'

export default function Auth({ onLogin, onClose }) {
  const [mode, setMode] = useState('login'); const [form, setForm] = useState({ name: '', email: '', password: '' }); const [error, setError] = useState('')
  const submit = async (event) => { event.preventDefault(); setError(''); try { if (mode === 'register') onLogin(await registerAccount(form)); else if (mode === 'reset') { await resetPassword(form); setMode('login') } else onLogin(await loginAccount(form)) } catch (err) { setError(err.message) } }
  return <section className="auth-card"><button className="auth-close" onClick={onClose}>×</button><p className="kicker">FINDAM ACCOUNT</p><h1>{mode === 'login' ? 'Welcome back' : mode === 'register' ? 'Create your account' : 'Reset your password'}</h1><form onSubmit={submit}>{mode === 'register' && <label>Full name<input required value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} /></label>}<label>Email<input required type="email" value={form.email} onChange={e => setForm({ ...form, email: e.target.value })} /></label><label>Password<input required minLength="8" type="password" value={form.password} onChange={e => setForm({ ...form, password: e.target.value })} /></label>{error && <p className="form-error">{error}</p>}<button className="primary">{mode === 'login' ? 'Log in' : mode === 'register' ? 'Create account' : 'Reset password'}</button></form><div className="auth-links"><button onClick={() => setMode(mode === 'login' ? 'reset' : 'login')}>{mode === 'login' ? 'Forgot password?' : 'Back to login'}</button><button onClick={() => setMode(mode === 'register' ? 'login' : 'register')}>{mode === 'register' ? 'Already registered? Log in' : 'Create an account'}</button></div></section>
}

export function Dashboard({ user, token, onLogout, go }) {
  const [items, setItems] = useState([]); const [favorites, setFavorites] = useState([]); const [inquiries, setInquiries] = useState([]); const [active, setActive] = useState('overview'); const [error, setError] = useState(''); const [drafts, setDrafts] = useState({}); const [busy, setBusy] = useState('')
  const refresh = () => { getMyListings(token).then(setItems).catch(e => setError(e.message)); getInquiries(token).then(setInquiries).catch(() => {}); const visitor = localStorage.getItem('findam-visitor-id'); if (visitor) getFavorites(visitor).then(setFavorites).catch(() => {}) }
  useEffect(refresh, [token])
  const reply = async (id) => { const text = (drafts[id] || '').trim(); if (!text) return; setBusy(id); try { await replyToInquiry(id, text, token); setDrafts({ ...drafts, [id]: '' }); refresh() } catch (e) { setError(e.message) } finally { setBusy('') } }
  const pending = items.filter(x => x.status === 'pending').length; const approved = items.filter(x => x.status === 'confirmed' || x.verified).length
  return <section className="dashboard-page"><div className="shell"><div className="dashboard-head"><div><p className="kicker">PERSONAL DASHBOARD</p><h1>Good to see you, {user.name || 'there'}.</h1><p>Manage rental listings and tenant conversations.</p></div><button className="secondary" onClick={onLogout}>Log out</button></div><div className="dashboard-layout"><aside className="dashboard-nav"><button className={active === 'overview' ? 'selected' : ''} onClick={() => setActive('overview')}>Overview</button><button className={active === 'listings' ? 'selected' : ''} onClick={() => setActive('listings')}>My listings</button><button className={active === 'profile' ? 'selected' : ''} onClick={() => setActive('profile')}>My profile</button><button className={active === 'inquiries' ? 'selected' : ''} onClick={() => setActive('inquiries')}>Inquiries <span>{inquiries.length}</span></button><button onClick={() => go('saved')}>Saved homes <span>♥</span></button><button className="mobile-post" onClick={() => go('list')}>+ Post a property</button></aside><main className="dashboard-main">{active === 'overview' && <div className="stat-cards"><div><span>My listings</span><strong>{items.length}</strong></div><div><span>Approved</span><strong>{approved}</strong></div><div><span>In review</span><strong>{pending}</strong></div><div><span>Inquiries</span><strong>{inquiries.length}</strong></div></div>}{active === 'listings' && <div className="dashboard-card"><h2>My listings</h2><ListingTable items={items} go={go} /></div>}{active === 'profile' && <div className="dashboard-card profile-card"><p className="kicker">ACCOUNT DETAILS</p><h2>My profile</h2><label>Full name<input value={user.name || ''} readOnly /></label><label>Email<input value={user.email} readOnly /></label></div>}{active === 'inquiries' && <InquiryPanel inquiries={inquiries} user={user} drafts={drafts} setDrafts={setDrafts} reply={reply} busy={busy} />}{error && <p className="form-error">{error}</p>}</main></div></div></section>
}

function InquiryPanel({ inquiries, user, drafts, setDrafts, reply, busy }) { return <div className="dashboard-card"><p className="kicker">RENTAL COMMUNICATION</p><h2>My inquiries</h2>{inquiries.length ? inquiries.map(item => { const owner = item.ownerId === user.id; return <article className="dashboard-card" key={item.id}><h3>{item.listing.title}</h3><small>{item.listing.city} · {owner ? 'Received from tenant' : 'Sent to owner'} · {item.status}</small>{item.messages.map((entry, index) => <p key={index}><b>{entry.senderId === user.id ? 'You' : 'Other participant'}:</b> {entry.text}<br /><small>{new Date(entry.createdAt).toLocaleString()}</small></p>)}{owner && <div className="bot-input"><input value={drafts[item.id] || ''} onChange={e => setDrafts({ ...drafts, [item.id]: e.target.value })} placeholder="Reply to tenant" /><button disabled={busy === item.id} onClick={() => reply(item.id)}>↗</button></div>}</article> }) : <p className="admin-muted">No rental inquiries yet.</p>}</div> }
function ListingTable({ items, go }) { return <div className="listing-rows">{items.length ? items.map(item => <div className="listing-row" key={item.id}><div className="listing-thumb">⌂</div><div><b>{item.title}</b><small>{item.city} · {Number(item.price || 0).toLocaleString()} FCFA</small></div><span className={'status ' + (item.status || 'pending')}>{item.status || 'pending'}</span></div>) : <div className="dashboard-empty"><p>No listings yet.</p><button className="text-button" onClick={() => go('list')}>Create your first listing →</button></div>}</div> }
