import { useEffect, useState } from 'react'
import { getMyListings, loginAccount, registerAccount, resetPassword } from '../api.js'

export default function Auth({ onLogin, onClose }) {
  const [mode, setMode] = useState('login'); const [form, setForm] = useState({ name: '', email: '', password: '' }); const [error, setError] = useState(''); const [message, setMessage] = useState('')
  const submit = async (event) => { event.preventDefault(); setError(''); setMessage(''); try { if (mode === 'register') { const result = await registerAccount(form); onLogin(result) } else if (mode === 'reset') { const result = await resetPassword(form); setMessage(result.message); setMode('login') } else onLogin(await loginAccount(form)) } catch (err) { setError(err.message) } }
  return <section className="auth-card"><button className="auth-close" onClick={onClose}>×</button><p className="kicker">FINDAM ACCOUNT</p><h1>{mode === 'login' ? 'Welcome back' : mode === 'register' ? 'Create your account' : 'Reset your password'}</h1><p className="lead">{mode === 'register' ? 'Post properties, manage listings and save homes in one place.' : 'Your account keeps your listings and favourites secure.'}</p><form onSubmit={submit}>{mode === 'register' && <label>Full name<input required value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} /></label>}<label>Email<input required type="email" value={form.email} onChange={e => setForm({ ...form, email: e.target.value })} /></label><label>{mode === 'reset' ? 'New password' : 'Password'}<input required minLength="8" type="password" value={form.password} onChange={e => setForm({ ...form, password: e.target.value })} /></label>{error && <p className="form-error">{error}</p>}{message && <p className="form-success">{message}</p>}<button className="primary">{mode === 'login' ? 'Log in' : mode === 'register' ? 'Create account' : 'Reset password'}</button></form><div className="auth-links">{mode === 'login' && <button onClick={() => setMode('reset')}>Forgot password?</button>}<button onClick={() => setMode(mode === 'register' ? 'login' : 'register')}>{mode === 'register' ? 'Already have an account? Log in' : 'Create an account'}</button></div></section>
}

export function Dashboard({ user, token, onLogout, go }) { const [items, setItems] = useState([]); const [error, setError] = useState(''); useState(() => { import('../api.js').then(({ getMyListings }) => getMyListings(token).then(setItems).catch(e => setError(e.message))) }); return <section className="shell section"><p className="kicker">MY ACCOUNT</p><h1 className="page-title">Hello, {user.name || user.email}</h1><div className="dashboard-grid"><article><h2>My profile</h2><p>{user.email}</p><p>Role: {user.role}</p><button className="secondary" onClick={onLogout}>Log out</button></article><article><h2>My listings</h2>{error && <p className="form-error">{error}</p>}{items.length ? items.map(item => <div className="status-row" key={item.id}><b>{item.title}</b><span className={`status ${item.status}`}>{item.status || 'pending'}</span><small>{item.city} · {item.price.toLocaleString()} FCFA</small></div>) : <p>No listings yet. <button className="text-button" onClick={() => go('list')}>Post your first property →</button></p>}</article><article><h2>Favorites</h2><p>Your saved homes are available from the heart icon in the navigation.</p><button className="secondary" onClick={() => go('saved')}>View favorites</button></article></div></section> }
