import { useEffect, useState } from 'react'
import { getFavorites, getMyListings, loginAccount, registerAccount, resetPassword } from '../api.js'

export default function Auth({ onLogin, onClose }) {
  const [mode, setMode] = useState('login'); const [form, setForm] = useState({ name: '', email: '', password: '' }); const [error, setError] = useState(''); const [message, setMessage] = useState('')
  const submit = async (event) => { event.preventDefault(); setError(''); try { if (mode === 'register') onLogin(await registerAccount(form)); else if (mode === 'reset') { setMessage((await resetPassword(form)).message); setMode('login') } else onLogin(await loginAccount(form)) } catch (err) { setError(err.message) } }
  return <section className="auth-card"><button className="auth-close" onClick={onClose}>×</button><p className="kicker">FINDAM ACCOUNT</p><h1>{mode === 'login' ? 'Welcome back' : mode === 'register' ? 'Create your account' : 'Reset your password'}</h1><p className="lead">Manage your homes, listings and property activity securely.</p><form onSubmit={submit}>{mode === 'register' && <label>Full name<input required value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} /></label>}<label>Email<input required type="email" value={form.email} onChange={e => setForm({ ...form, email: e.target.value })} /></label><label>{mode === 'reset' ? 'New password' : 'Password'}<input required minLength="8" type="password" value={form.password} onChange={e => setForm({ ...form, password: e.target.value })} /></label>{error && <p className="form-error">{error}</p>}{message && <p className="form-success">{message}</p>}<button className="primary">{mode === 'login' ? 'Log in' : mode === 'register' ? 'Create account' : 'Reset password'}</button></form><div className="auth-links">{mode === 'login' && <button onClick={() => setMode('reset')}>Forgot password?</button>}<button onClick={() => setMode(mode === 'register' ? 'login' : 'register')}>{mode === 'register' ? 'Already registered? Log in' : 'Create an account'}</button></div></section>
}

export function Dashboard({ user, token, onLogout, go }) {
  const [items, setItems] = useState([]); const [favorites, setFavorites] = useState([]); const [active, setActive] = useState('overview'); const [error, setError] = useState('')
  useEffect(() => { getMyListings(token).then(setItems).catch(e => setError(e.message)); const visitor = localStorage.getItem('findam-visitor-id'); if (visitor) getFavorites(visitor).then(setFavorites).catch(() => {}) }, [token])
  const pending = items.filter(x => x.status === 'pending').length; const approved = items.filter(x => x.status === 'confirmed' || x.verified).length
  return <section className="dashboard-page"><div className="shell"><div className="dashboard-head"><div><p className="kicker">PERSONAL DASHBOARD</p><h1>Good to see you, {user.name || 'there'}.</h1><p>Keep track of your Findam activity from one simple workspace.</p></div><button className="secondary" onClick={onLogout}>Log out</button></div><div className="dashboard-layout"><aside className="dashboard-nav"><button className={active === 'overview' ? 'selected' : ''} onClick={() => setActive('overview')}>Overview</button><button className={active === 'listings' ? 'selected' : ''} onClick={() => setActive('listings')}>My listings</button><button className={active === 'profile' ? 'selected' : ''} onClick={() => setActive('profile')}>My profile</button><button onClick={() => go('saved')}>Saved homes <span>♥</span></button><button className="mobile-post" onClick={() => go('list')}>+ Post a property</button></aside><main className="dashboard-main">{active === 'overview' && <><div className="stat-cards"><div><span>My listings</span><strong>{items.length}</strong><small>Properties submitted</small></div><div><span>Approved</span><strong>{approved}</strong><small>Live on Findam</small></div><div><span>In review</span><strong>{pending}</strong><small>Awaiting verification</small></div><div><span>Saved homes</span><strong>{favorites.length}</strong><small>Your shortlist</small></div></div><div className="dashboard-card welcome-card"><div><p className="kicker">READY TO MOVE?</p><h2>List a property with confidence.</h2><p>Submit your property details and our verification team will guide you through the next step.</p><button className="primary" onClick={() => go('list')}>Post a property →</button></div><div className="welcome-mark">⌂</div></div><ListingTable items={items.slice(0, 5)} go={go} /></>}{active === 'listings' && <div className="dashboard-card"><div className="card-heading"><div><p className="kicker">PROPERTY MANAGEMENT</p><h2>My listings</h2></div><button className="primary" onClick={() => go('list')}>+ New listing</button></div><ListingTable items={items} go={go} /></div>}{active === 'profile' && <div className="dashboard-card profile-card"><p className="kicker">ACCOUNT DETAILS</p><h2>My profile</h2><div className="profile-avatar">{(user.name || user.email).slice(0, 1).toUpperCase()}</div><label>Full name<input value={user.name || ''} readOnly /></label><label>Email<input value={user.email} readOnly /></label><p className="profile-role">Account type: <b>{user.role || 'user'}</b></p></div>}{error && <p className="form-error">{error}</p>}</main></div></div></section>
}

function ListingTable({ items, go }) { return <div className="dashboard-card listing-table"><div className="card-heading"><div><p className="kicker">RECENT ACTIVITY</p><h2>Your property listings</h2></div></div>{items.length ? <div className="listing-rows">{items.map(item => <div className="listing-row" key={item.id}><div className="listing-thumb" style={{ '--hue': item.hue || 28 }}>⌂</div><div><b>{item.title}</b><small>{item.city} · {Number(item.price || 0).toLocaleString()} FCFA</small></div><span className={`status ${item.status || (item.verified ? 'confirmed' : 'pending')}`}>{item.status || (item.verified ? 'confirmed' : 'pending')}</span></div>)}</div> : <div className="dashboard-empty"><span>⌂</span><p>You have not posted a property yet.</p><button className="text-button" onClick={() => go('list')}>Create your first listing →</button></div>}</div> }
